services:
  # app:
  #   build: .
  #   container_name: my_app
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - "8081:8081"
  #   restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myartverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailslurper:
    image: marcopas/docker-mailslurper
    container_name: mailslurper
    ports:
      - "9091:8080"
      - "8085:8085"
      - "2500:2500"
    restart: unless-stopped
    depends_on:
      - postgres

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/localstack/data
    volumes:
      - "localstack_data:/var/localstack/data"

    restart: unless-stopped

volumes:
  postgres_data:
  localstack_data:
