services:

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: myfursona
      POSTGRES_USER: myfursona
      POSTGRES_DB: myfursona
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass TsimdoCBK5roPYhrVLnLj8Us1mOHfgIYoGP5kaeB
