services:
  # app:
  #   build: .
  #   container_name: my_app
  #   depends_on:
  #     - postgres
  #     - minio
  #   env_file:
  #     - .env
  #   ports:
  #     - "8081:8081"
  #   restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myartverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: my_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  mailslurper:
    image: marcopas/docker-mailslurper
    container_name: mailslurper
    ports:
      - "9091:8080"
      - "8085:8085"
      - "2500:2500"
    restart: unless-stopped
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
