services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: myfursona
      POSTGRES_USER: myfursona
      POSTGRES_DB: myfursona
    ports:
      - 5432:5432
