version: "3.8"
services:
  # app:
  #   build: .
  #   container_name: my_app
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - "8081:8081"
  #   restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myartverse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  mailslurper:
    image: marcopas/docker-mailslurper
    container_name: mailslurper
    ports:
      - "9091:8080"
      - "8085:8085"
      - "2500:2500"
    restart: unless-stopped
    depends_on:
      - postgres
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9092:9090"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=MYARTVERSE
      - MINIO_ROOT_PASSWORD=PASSWORD
    command: server /data --console-address ":9090"

volumes:
  postgres_data:
