GET http://localhost:8080/v1/auth/whoami
Accept: application/json

###
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "login":"test2@test.local",
  "password": "test_pass2"
}



###
GET http://localhost:8080/v1/auth/verify/fb68f674-5e0a-4799-8ceb-85aa9dcc2516
Accept: application/json

###
POST http://localhost:8080/v1/auth/register
Content-Type: application/json

{
  "username": "Test2",
  "email": "test2@test.local",
  "password": "test_pass2",
  "captcha": "test"
}

###

