GET http://localhost:8080/v1/auth/verify/4df87686-1700-4446-8af5-24d1286c1b63
Accept: application/json

###
POST http://localhost:8080/v1/auth/register
Content-Type: application/json

{
  "username": "Test2",
  "email": "test2@test.local",
  "password": "test_pass2",
  "captcha": "test"
}

###
